[package]
name = "beet_server_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true
readme.workspace = true
description = "Simple file server with live reload"
repository.workspace = true


[features]
"rustls" = ["dep:axum-server", "axum-server/tls-rustls"]

[dependencies]
beet_utils.workspace = true
beet_fs.workspace = true
## utils
anyhow.workspace = true
thiserror.workspace = true
extend.workspace = true
clap.workspace = true
colorize.workspace = true
glob.workspace = true

# async
futures.workspace = true
tokio.workspace = true

# http
http = "1"
axum = "0.8"
axum-extra = "0.10"
axum-server = { version = "0.7", optional = true, features = ["tls-rustls"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["fs", "cors"] }
tower-livereload = "0.9"


[dev-dependencies]
sweet.workspace = true
