[package]
name = "beet_stack"
version.workspace = true
edition.workspace = true
description = "An opinionated semantic layer between applications and interfaces"
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[features]
default = ["interface", "tui"]
interface = ["serde"]
serde = ["dep:serde","beet_core/json","beet_core/postcard"]
tui = ["interface", "dep:bevy_ratatui", "dep:ratatui"]

[dependencies]
beet_core = { workspace = true, features = ["exchange"] }
bevy.workspace = true
extend.workspace = true
thiserror.workspace = true
variadics_please.workspace = true

serde = {workspace = true, optional=true}
bevy_ratatui = {workspace = true, optional=true}
ratatui = {workspace = true, optional=true, features=["crossterm"]}

[dev-dependencies]
beet_core = { workspace = true, features = ["testing"] }


[target.'cfg(target_arch = "wasm32")'.dev-dependencies]




[[test]]
name = "interface"
path = "tests/interface.rs"
required-features = ["interface"]
