[package]
name = "beet_stack"
version.workspace = true
edition.workspace = true
description = "An opinionated semantic layer between applications and interfaces"
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[features]
default = ["interface"]
interface = ["dep:serde","dep:serde_json","dep:postcard","beet_core/exchange"]

[dependencies]
beet_core = { workspace = true }
bevy.workspace = true
extend.workspace = true
thiserror.workspace = true
variadics_please.workspace = true

serde = {workspace = true, optional=true}
serde_json = {workspace = true, optional=true}
postcard = {workspace = true, optional=true}

[dev-dependencies]
beet_core = { workspace = true, features = ["testing"] }


[target.'cfg(target_arch = "wasm32")'.dev-dependencies]




[[test]]
name = "stack"
path = "tests/stack.rs"
required-features = ["interface"]
