max_width = 80 # Maximum width of each line
tab_spaces = 2 # Number of spaces per tab
indentation_style = "Tabs" # "Tabs", "Spaces" or "Auto"
newline_style = "Unix" # "Unix", "Windows" or "Auto"
attr_value_brace_style = "WhenRequired" # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
macro_names = [ "beet::rsx", "rsx" ] # Macro names which will be formatted
closing_tag_style = "Preserve" # "Preserve", "SelfClosing" or "NonSelfClosing"

# Attribute values can be formatted by custom formatters
# Every attribute name may only select one formatter (this might change later on)
# [attr_values]
# class = "Tailwind" # "Tailwind" is the only attribute value formatter available for now