[package]
name = "beet_flow_macros"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
anyhow.workspace = true
proc-macro2.version = "1"
syn.version = "2"
quote.version = "1"
toml_edit = "0.22"
extend.workspace = true


[dev-dependencies]
bevy.workspace = true
beet_flow.workspace = true
