[package]
name = "beet_tool"
version.workspace = true
edition.workspace = true
description = "Entities as async functions."
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
exchange = ["beet_core/exchange"]
serde = ["dep:serde"]

[dependencies]
beet_core = { workspace = true }
bevy.workspace = true
extend.workspace = true
serde = { workspace = true, optional = true }
[dev-dependencies]
beet_core = { workspace = true, features = ["testing"] }
