name: ðŸ”Ž Test - Rsx
on:
  workflow_dispatch:
  # pull_request:
  #   paths:
  #     - 'Cargo.lock'
  #     - '.github/workflows/test-rsx.yml'
  #     - 'crates_rsx/**'
  # push:
  #   branches:
  #     - main
  #     - release-*
  #   paths:
  #     - 'Cargo.lock'
  #     - '.github/workflows/test-rsx.yml'
  #     - 'crates_rsx/**'
env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: ðŸ“‚ Checkout
      uses: actions/checkout@v4
    - name: ðŸ“‚ Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        # TODO - once the beet cli is binstallable we should be able to share cache between workflows because setup will be cheap
        key: ${{ runner.os }}-cargo-${{ github.workflow }}-${{ hashFiles('**/Cargo.lock') }}-v0
    - name: ðŸ”¨ðŸ“‹ Install Just
      uses: extractions/setup-just@v1
    - name: ðŸ”¨ Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x  
    - name: ðŸ”¨ Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
    - name: ðŸ”¨ Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: ðŸ”¨ Install cargo binstall
      uses: cargo-bins/cargo-binstall@main
    - name: ðŸ”¨ Install wasm bindgen cli
      run: cargo binstall wasm-bindgen-cli --version 0.2.100    || true
    - name: ðŸ”¨ Install sweet cli
      run: cargo binstall sweet-cli --version 0.3.0-rc.3        || true
    - name: ðŸ“‹ Init repo
      run: just init-rsx
    - name: ðŸ”Ž Test
      run: just test-rsx